### ISSUE TITLE
player.get("ended") returned undefined before refreshing page

### ISSUE THREAD

**Issue by yankai-wang** [empiricaly/empirica#360] opened 2023-07-18 02:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I wanna use `player.get("ended")` to display different content in the Sorry page. But it returns `undefined` until the page is refreshed once. 

### Empirica Version

```text
Version: v1.4.6
SHA:     877d1e0
Branch:  main
Time:    2023-07-16T15:01:49Z

Client:  1.4.6
Server:  1.4.6
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment] 2023-07-23 08:27
I can confirm the `ended` field is not available in the exitSteps callback. It does load asynchronously after that. This is a problem if you use it in the exitSteps callback to determine which steps to show depending on the value of ended.

I've pushed a fix for this in a prerelease. Since it's a prerelease, updating is a little different:

1. replace the contents of `.empirica/release` with `version: v1.4.6`
1. go into `client/` and run `empirica npm install @empirica/core@next`
1. go into `server/` and run the same npm command.

Please let me know how it goes.

**Comment by npaton** [comment] 2023-08-19 07:20
Released.

**Closed by npaton** 2023-08-19 07:20 UTC
Labels: bug
