### ISSUE TITLE
refresh on exit survey is heavy

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#25] opened 2018-06-11 20:45 UTC
It is weird that refreshing the page on the exit survey can break the browser (i.e., not responding) and feels really heavy and slow. The console shows `Clock discrepancy detected. Attempting re-sync.` which I don't know if related to this issue.

**Comment by npaton** [comment] 2018-06-12 06:16
I cannot reproduce this issue. Is it happening on the empirica default app? If it is happening on a forked experiment, I recommend moving this ticket over to that experiment so it can be reproduced.

Note that `Clock discrepancy detected. Attempting re-sync` is unrelated, it is the clock sync we need to sync stage timers, it appears on any page, any time there is a clock discrepancy, which is very common and not a costly operation.

**Closed** 2018-06-12 14:32 UTC
Labels: invalid
